- name: install pip
  apt: name={{ item }} state=latest
  become: yes
  with_items:
    - python-pip

- name: install python dev packages
  pip: name={{ item }} state=latest
  become: yes
  with_items:
    - pip
    - virtualenv
    - virtualenvwrapper
